### ISSUE TITLE
Add text filter query to URL and filter on render

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#122]
We should add a parameter to the URL according to the current "Text Filter" component's state. This will allow for people to share specific issues, organizations and repos. An example of how this could look is: `https://devpool.directory/?q=ubiquity-os-marketplace` where on page load a checker function should be called to set the text filter to be `ubiquity-os-marketplace` from the URL. The filter's state should be made persistent which it currently is not, this means that toggling between directory and proposals should keep the filter on.

**Comment by zugdev** [comment]
@0x4007 can you please give your opinion in this proposal? I believe it's cool specially with partners in mind.

**Comment by 0x4007** [comment]
I use the text filter for this purpose. Just type in the org name and append a / at the end. 

It might not be the most intuitive but it works fine.

**Comment by 0x4007** [comment]
> it would be ideal to be able to generate a link that automatically filter's by it's organization.

- We can add this to #118

**Comment by 0x4007** [comment]
I think it could be interesting to add the query param to prefill the search filter and to ensure the page acts as expected. Basically, right now, if you toggle between the proposals and tasks view, it will show everything and not consider the value inside of the text filter box so that would also need to be fixed. 

`https://devpool.directory/?q=ubiquity-os-marketplace` is an example of how this can look. Perhaps the search filter box should automatically change the search query in the url bar on every key stroke so that the user can conveniently search for what they want, and then copy/paste the URL straight from their browser UI when they see the filtered views they want.

In addition, perhaps within the render function we can always check the current search query state so that it filters every time the render function is called. This should automatically solve for when we toggle between the proposals and tasks view.

**Comment by zugdev** [comment]
> In addition, perhaps within the render function we can always check the current search query state so that it filters every time the render function is called. This should automatically solve for when we toggle between the proposals and tasks view.

Yes that's how the proposal filter runs and it should be standard. I'll rewrite the issue's spec.

**Comment by zugdev** [comment]
Since the URL would hypothetically keep the filter, we should probably add a little 'x' icon to quickly clear it. 

Imagine you click on a link and the toolbar opens up like this

![image](https://github.com/user-attachments/assets/c54ba139-7e30-4292-8f96-fc7ce26fbc54)

it's no longer obvious that this field is a text search input field.

We could add a really small magnifying glass icon to let this be clear and show the 'x' icon when selected.

**Comment by 0x4007** [comment]
Another idea is to copy the animation we use to highlight the login with GitHub button when rate limited. 

It's a css animation that draws attention to the element

**Comment by 0x4007** [comment]
I suppose that it might be a good idea to use more space for the search bar as well, now that its a more capable feature. Hope that you can wrangle with flexbox or whatever to make it naturally fill up the empty space. For that I'll add more time to this.

**Comment by zugdev** [comment]
Can you assign me here?

**Comment by zugdev** [comment]
This bounty seems to be tied to the old price label, is this correct?

Might interest @gentlementlegen 

Also this was merged but I don't see it on work.ubq.fi

**Comment by gentlementlegen** [comment]
@zugdev the reason for the price is that it was closed without you being assigned so you actually didn't get the reward at all

**Comment by zugdev** [comment]
> @zugdev the reason for the price is that it was closed without you being assigned so you actually didn't get the reward at all

oh ok, there is already an issue up to assign on pull merged which should prevent this later.
