### ISSUE TITLE
Stale data is displayed without a full cache clean

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/work.ubq.fi#14]
It seems that https://work.ubq.fi/ displays tickets that are closed, updated, or moved, regardless of their real state in the GitHub repo. This can be fixed by emptying the browser cache and reloading the page, which is an abnormal behavior.

Expected behavior:
The list of available bounties should reflect the available issues in the corresponding GitHub repositories.

**Comment by 0x4007** [comment]
I originally was thinking of setting for four hours, but I added extra time because I know that this will be complicated to test. I am expecting that when the project is completed, we will find some strange edge case a few days later and re-open the issue lol

Not sure if unit testing is viable here but that would be one way to prove that its all good (just seems like a lot of extra work which might not be totally necessary.)

**Comment by gentlementlegen** [comment]
I think the best way to test this case would be to mock the whole networking part, which indeed would take quite some time to set up since I don't think there is any test implemented yet. But it's still worth it to track this issue I think, because it might be troublesome for people arriving in the DevPool and only finding tickets that were closed already.

**Comment by 0x4007** [comment]
> But it's still worth it to track this issue I think, because it might be troublesome for people arriving in the DevPool and only finding tickets that were closed already.

Yes this task is already funded and ready to be worked on.

**Comment by 0x4007** [comment]
Hey @FernandVEYRIER just as a heads up, my expectation is that the flags are handled correctly:

```
{
    "isNew": boolean,
    "isModified": boolean,
    "preview": GitHubIssue,
    "full": GitHubIssue
}
```

`isNew` indicates that it has been added to the directory since you last viewed it on your client. There is a visual indicator of a bright cyan bar on the left side. 

`isModified` indicates that the issue specification has been modified since you last viewed it on your client. There WILL be a visual indicator of a bright orange bar on the left side. 

---

Both have been implemented poorly, but I imagine that once this code is refactored those could be straightforward to check for.

**Comment by gentlementlegen** [comment]
@pavlovcik The first main problem is that issues don't get refreshed at all if there is already a cache. Inside of `fetchAndDisplayPreviewsFromCache` (file `fetch-and-display-preview.ts`) new issues are fetched only if the cache is empty. I guess the intent was to avoid the very tight GitHub limitations when it comes to data fetching, while not logged-in. Since we don't use SSR, I understand that you don't want to expose the company's GitHub PAT either. Maybe a solution would be to time the cache by giving it a 15 minutes lifespan or something similar, which would ensure it gets refreshed at some point, or even a refresh button.

**Comment by 0x4007** [comment]
> by giving it a 15 minutes lifespan or something similar

This seems like a good idea because our sync on the backend is every 15 minutes. 

Although at the risk of over engineering: I'm curious if these parameters are optimal.

**Comment by gentlementlegen** [comment]
> > by giving it a 15 minutes lifespan or something similar
> 
> This seems like a good idea because our sync on the backend is every 15 minutes.
> 
> Although at the risk of over engineering: I'm curious if these parameters are optimal.

Let's do that for now, I think it would be the most straightforward solution to our problem. I think that the ideal setup would be to have SSR within our website so we could keep the PAT hidden on the server, and users would not have to login and on our side we would bypass the API restrictions since we would be logged in. I didn't want to get into that because we don't use any framework that offers it out of the box like Nextjs and setting it up manually was more annoying most likely.
