### ISSUE TITLE
Error toast is not shown properly

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/work.ubq.fi#50]
When errors occurs, an error toast should be shown in the UI describing the error to the user. 

Some example of use cases are:
- the user got rate limited
- the endpoint in unreachable

Currently, nothing is shown in these scenarios, which leads the user to think that the broken UI is normal.

Tasks to be carried out:
- show the toast properly when errors occur
- add related tests to avoid regression

**Comment by gentlementlegen** [comment]
@jordan-ae please feel free to carry on your task here, as it is related and you've already done research
https://github.com/ubiquity/work.ubq.fi/pull/49

**Comment by jordan-ae** [comment]
Hey @0x4007 I don't understand why my PR was closed and I was unassigned. I've been working on this for a while now and was on the right track. The issue was close to being completed (just pending review). I submitted my initial PR in a few hours of taking the issue and have made every change requested by @rndquu & @gentlementlegen. I believe there must be a better way of handling situations like this. I could've implemented any suggestion you gave me asap rather than unassigning me and closing the PR when I was clearly on the right track.

Again the time and effort, the back and forth reviews all that just lost. To iterate on something for this long as a contributor and have it just closed like that last minute isn't really helpful for motivation. I know you guys are very elitist back here but there's honestly better way to build community spirit and push people to give their best other than this.

**Comment by 0x4007** [comment]
> Hey @0x4007 I don't understand why my PR was closed and I was unassigned. 

https://github.com/ubiquity/work.ubq.fi/pull/51#issuecomment-2147113755

> I've been working on this for a while now and was on the right track. 

You are on week three of a `<4 hour` task; past the deadline. Your latest approach does not solve the specified problem correctly. I provided an example of why in my comment. 

> Again the time and effort, the back and forth reviews all that just lost. To iterate on something for this long as a contributor and have it just closed like that last minute isn't really helpful for motivation. I know you guys are very elitist back here but there's honestly better way to build community spirit and push people to give their best other than this.

I understand the frustration that comes with having a pull closed after considerable effort, but please remember that code reviews require significant time from our paid team members. This process is meant to maintain the quality and efficiency of our project.

Due to the urgency and simplicity of this task, I stepped in to ensure it was completed promptly, as it has impacted my demos of the product. 

I have a vested interest in ensuring that timely progress is made on all fronts for Ubiquity.

**Comment by jordan-ae** [comment]
Okay @0x4007  I understand! But I Didn't take 3 weeks to come up with a solution though. The review took three weeks. Reviews aren't super fast and the approach I took was that proposed by the team. I'll do better next time though. Thanks
