### ISSUE TITLE
Text Filter Seems Broken

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#66]
I put a very specific search query, so I expect it to only filter down to a single task. However it seems to be broken. 

It could be related to an invalid issue preview in my cache, as you can see that the error was thrown. 

![work ubq fi_ (1)](https://github.com/ubiquity/work.ubq.fi/assets/4975670/f7caf10a-948d-4c69-9da6-d1ec69a552a3)

**Comment by Sadaf-A** [comment]
Hey @0x4007, I'm getting an error when I try to login to GitHub it says "provider not found"

**Comment by 0x4007** [comment]
Can you do a git blame on the code and tag who implemented it?

**Comment by Sadaf-A** [comment]
> Can you do a git blame on the code and tag who implemented it?

It was actually because of supabase I Hadn't enabled GitHub provider and setup the OAuth app. I think that's worth mentioning in the documentation.

<img width="1512" alt="Screenshot 2024-07-12 at 3 48 59 PM" src="https://github.com/user-attachments/assets/12366446-dc01-49eb-8477-4b6343da3c0c">
Earlier I was getting the same error as you but now the text filter is working as expected for me has this issue already been resolved?

**Comment by 0x4007** [comment]
![image](https://github.com/user-attachments/assets/e71822cd-77fd-4619-afe3-333fdbdcc208)

It needs to handle broken cache then. I have some sort of invalid issues listed and the search immediately crashes with these. Make sure to just handle these invalid ones with a try catch of sorts.

**Comment by 0x4007** [comment]
Seems cache related as I no longer have this problem.
